import search
print("| ------------------------------ |")
print("| --- Welcome To AMST Client --- |")
print("| ------------------------------ |")
print("|  ----Please Enter Command----  |")
print("| ------------------------------ |")
print("| Command ID: 1 - Search         |")
print("| Command ID: 2 - Review         |")
print("| Command ID: 3 - Recommend      |")
print("| Command ID: 4 - Admin Section  |")
print("| ------------------------------ |")
print("| -- Please Enter Command ID: -- |")
print("| ------------------------------ |")
id = input("Command ID: > ")
if id == "1":
    print("| ------------------------------ |")
    print("| -------- AMST Client --------- |")
    print("| ------------------------------ |")
    print("| ------- Running Search ------- |")
    print("| ------------------------------ |")
    search.run()
elif id == "2":
    print("| ------------------------------ |")
    print("| -------- AMST Client --------- |")
    print("| ------------------------------ |")
    print("| --- Running Review System  --- |")
    print("| ------------------------------ |")
elif id == "3":
    print("| ------------------------------ |")
    print("| -------- AMST Client --------- |")
    print("| ------------------------------ |")
    print("| -- Running Recomend Service  --|")
    print("| ------------------------------ |")
elif id == "4":
    print("| ------------------------------ |")
    print("| -------- AMST Client --------- |")
    print("| ------------------------------ |")
    print("| ---- Entering Admin Mode ----  |")
    print("| ------------------------------ |")
else:
    print("| ------------------------------ |")
    print("| ----- Unvalid Command ID ----- |")
    print("| ------------------------------ |")